# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3d0db8cfb963ecc484d1b50d3ba0b94"
application_url = "https://collections-bigger-behalf-current.trycloudflare.com"
embedded = true
name = "new-order-app"
handle = "new-order-app-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders"

[auth]
redirect_urls = [
  "https://collections-bigger-behalf-current.trycloudflare.com/auth/callback",
  "https://collections-bigger-behalf-current.trycloudflare.com/auth/shopify/callback",
  "https://collections-bigger-behalf-current.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "zeeper-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
